import importlib.util
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
spec=importlib.util.spec_from_file_location("p",ROOT/"scripts"/"autonomous_research_planner.py")
p=importlib.util.module_from_spec(spec);spec.loader.exec_module(p)

agent={
 "watchlist_attention":[
  {"symbol":"LITE","level":"action","research_priority":88,"reasons":["单日大涨"],"run_count":1},
  {"symbol":"QQQ","level":"quiet","research_priority":40,"reasons":[]}
 ],
 "discovery_queue":[{"symbol":"XYZ","event_strength":"high","next_step":"核对官方事件"}]
}
evidence={"failure_attribution":{"external_outcome_reviews":[
 {"event_id":"e1","symbol":"IREN","title":"failure"},
 {"event_id":"e2","symbol":"IREN","title":"failure2"},
]}}
method={"methods":[{"method":"趋势确认","direct_validated_events":1,"context_validated_events":10}]}
out=p.build(agent,{},evidence,method,{}, {})
assert out["version"]=="6.14.3"
assert out["counts"]["open"]>=4
assert any(x["kind"]=="market_anomaly" and x["key"]=="LITE" for x in out["queue"])
assert any(x["kind"]=="failure_review" for x in out["queue"])
assert any(x["kind"]=="method_evidence_gap" for x in out["queue"])
assert any(x["kind"]=="discovery" and x["key"]=="XYZ" for x in out["queue"])
assert "automatic_order" in out["planner_policy"]["forbidden"]

prev={"queue":[out["queue"][0]]}
out2=p.build(agent,{},evidence,method,{},prev)
same=next(x for x in out2["queue"] if x["task_id"]==out["queue"][0]["task_id"])
assert same["run_count"]==2

# Persistent backlog: an old open task not regenerated by the current snapshot
# must survive until its review window expires.
prior_task={
    "task_id":"legacy-open-1","kind":"manual_research","key":"ABC",
    "title":"ABC · pending research","priority":71,"why_now":"pending",
    "questions":["q"],"evidence_sources":["x"],"status":"open",
    "review_window_days":30,"first_seen_at":"2026-10-01T00:00:00+00:00","run_count":2,
}
carry=build({}, {}, {}, {}, {}, {"queue":[prior_task]}, {}, {}, {}, {}, {}, {}, {})
row=next(x for x in carry["queue"] if x["task_id"]=="legacy-open-1")
assert row["carry_forward"] is True
assert row["status"]=="open"
assert carry["counts"]["carried_backlog"]>=1
assert carry["planner_policy"]["backlog_contract"]

print("PASS V6 autonomous research planner")

failure=next(x for x in out["queue"] if x["kind"]=="failure_review")
assert failure["key"]=="IREN"
assert failure["sample_count"]==2
assert failure["priority"]==68
live=next(x for x in out["queue"] if x["kind"]=="market_anomaly")
assert live["priority"]>=88
assert out["today"][0]["kind"]=="market_anomaly"

modules={"audit":{"coverage_ok":False},"modules":[{"id":"tab-engine","name":"核心策略信号","learning":"shadow_only"}]}
out3=p.build(agent,{},evidence,method,{}, {},modules)
assert any(x["kind"]=="architecture_gap" for x in out3["queue"])
assert any(x["kind"]=="module_learning_review" and x["key"]=="tab-engine" for x in out3["queue"])

cross={"level":"high","label":"高位跨资产背离","risk_hits":4}
out4=p.build(agent,{},evidence,method,{}, {},{},cross)
ca=next(x for x in out4["queue"] if x["kind"]=="cross_asset_divergence")
assert ca["priority"]==86
assert ca["key"]=="US_MARKET"
assert ca["divergence_level"]=="high"

breadth={"level":"fragile","label":"参与度脆弱 · 权重股主导","participation_score":31.5,"risk_hits":5,"combination_key":"B20_LOW|B50_LOW|SPY_RSP_GAP"}
regime={"level":"high","label":"跨资产压力 + 宽度脆弱共振","state_id":"CROSS_HIGH|BREADTH_FRAGILE|VIX_LOW"}
out5=p.build(agent,{},evidence,method,{}, {},{},cross,breadth,regime)
bi=next(x for x in out5["queue"] if x["kind"]=="breadth_intelligence")
rg=next(x for x in out5["queue"] if x["kind"]=="regime_combination")
assert bi["priority"]==88 and bi["key"]=="US_BREADTH"
assert rg["priority"]==92 and rg["key"]=="US_REGIME"
assert out5["today"][0]["kind"]=="regime_combination"

rebound_data={"leverage_rebound":{"available":True,"status":"candidate","label":"10%+回调后修复确认 · TQQQ/LEAPS对比","priority":84,"drawdown252":-0.12,"prompt":"进入工具比较窗口","source_method":{"author":"lionhill / 狮山巡礼","title":"TQQQ还是QQQ LEAPS"}}}
out6=p.build(agent,{},evidence,method,{}, {},{},cross,breadth,regime,rebound_data)
lr=next(x for x in out6["queue"] if x["kind"]=="leverage_rebound")
assert lr["key"]=="QQQ"
assert lr["priority"]==84
assert lr["qqq_drawdown"]==-0.12
assert "source_method_lionhill" in lr["evidence_sources"]
