-- V3.1: Covered Call Roll Up / Sell Put Roll Down & Out 管理器。
-- 在 Supabase SQL Editor 执行一次；所有业务表均按 auth.uid() 隔离。

alter table public.options_positions
  add column if not exists monitor_delta numeric check (monitor_delta between -1 and 1),
  add column if not exists delta_observation text check (delta_observation in ('close','intraday')),
  add column if not exists delta_observed_at timestamptz,
  add column if not exists watch_close_count integer not null default 0 check (watch_close_count >= 0),
  add column if not exists catalyst_confirmed boolean not null default false,
  add column if not exists strategy_note text,
  add column if not exists premium_chain_per_share numeric;

create table if not exists public.option_underlyings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade default auth.uid(),
  symbol text not null,
  shares integer not null default 0 check (shares >= 0),
  cost_basis numeric not null default 0 check (cost_basis >= 0),
  current_price numeric check (current_price >= 0),
  target_tranches jsonb not null default '[]'::jsonb,
  watch_delta numeric not null default 0.70 check (watch_delta > 0 and watch_delta < 1),
  urgent_delta numeric not null default 0.80 check (urgent_delta > 0 and urgent_delta <= 1),
  put_watch_delta numeric not null default 0.50 check (put_watch_delta > 0 and put_watch_delta < 1),
  put_urgent_delta numeric not null default 0.70 check (put_urgent_delta > 0 and put_urgent_delta <= 1),
  put_assignment_mode text not null default 'accept' check (put_assignment_mode in ('accept','avoid')),
  updated_at timestamptz not null default now(),
  unique (user_id, symbol),
  check (watch_delta < urgent_delta)
);

alter table public.option_underlyings
  add column if not exists put_watch_delta numeric not null default 0.50 check (put_watch_delta > 0 and put_watch_delta < 1),
  add column if not exists put_urgent_delta numeric not null default 0.70 check (put_urgent_delta > 0 and put_urgent_delta <= 1),
  add column if not exists put_assignment_mode text not null default 'accept' check (put_assignment_mode in ('accept','avoid'));

create table if not exists public.option_roll_journal (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade default auth.uid(),
  old_position_id bigint references public.options_positions(id) on delete set null,
  new_position_id bigint references public.options_positions(id) on delete set null,
  symbol text not null,
  strategy text not null check (strategy in ('covered_call','sell_put')),
  old_strike numeric not null,
  old_expiry date not null,
  new_strike numeric not null,
  new_expiry date not null,
  qty integer not null check (qty > 0),
  multiplier integer not null check (multiplier > 0),
  close_debit numeric not null check (close_debit >= 0),
  open_credit numeric not null check (open_credit >= 0),
  close_fee numeric not null default 0 check (close_fee >= 0),
  open_fee numeric not null default 0 check (open_fee >= 0),
  net_roll_cash numeric not null,
  cumulative_premium_per_share numeric not null,
  observation_type text not null check (observation_type in ('close','intraday')),
  catalyst_confirmed boolean not null default false,
  notes text,
  executed_at timestamptz not null default now()
);

alter table public.option_underlyings enable row level security;
alter table public.option_roll_journal enable row level security;

drop policy if exists "option_underlyings_private" on public.option_underlyings;
create policy "option_underlyings_private" on public.option_underlyings
for all using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "option_roll_journal_private" on public.option_roll_journal;
create policy "option_roll_journal_private" on public.option_roll_journal
for all using (user_id = auth.uid()) with check (user_id = auth.uid());

create index if not exists option_underlyings_user_symbol_idx
  on public.option_underlyings(user_id, symbol);
create index if not exists option_roll_journal_user_executed_idx
  on public.option_roll_journal(user_id, executed_at desc);

-- 一次数据库事务完成：关闭旧仓、建立新仓、连接两笔持仓、写入展期日志。
-- V3.1 仅支持整笔展期；如需分批，请在首次建仓时拆成多笔持仓。
create or replace function public.record_option_roll(
  p_old_position_id bigint,
  p_new_strike numeric,
  p_new_expiry date,
  p_close_debit numeric,
  p_open_credit numeric,
  p_close_fee numeric default 0,
  p_open_fee numeric default 0,
  p_observation_type text default 'close',
  p_catalyst_confirmed boolean default false,
  p_notes text default null
) returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_old public.options_positions%rowtype;
  v_new_id bigint;
  v_units numeric;
  v_prior_chain numeric;
  v_chain numeric;
  v_net_cash numeric;
  v_realized numeric;
  v_strategy text;
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;
  if p_new_strike <= 0 or p_new_expiry is null or p_close_debit < 0 or p_open_credit < 0
     or p_close_fee < 0 or p_open_fee < 0 then raise exception 'INVALID_ROLL_INPUT'; end if;
  if p_observation_type not in ('close','intraday') then raise exception 'INVALID_OBSERVATION_TYPE'; end if;

  select * into v_old from public.options_positions
  where id = p_old_position_id and user_id = auth.uid() for update;
  if not found then raise exception 'POSITION_NOT_FOUND'; end if;
  if coalesce(v_old.status, 'open') <> 'open' then raise exception 'POSITION_NOT_OPEN'; end if;
  if lower(v_old.side) <> 'short' or lower(v_old.opt_type) not in ('call','put') then
    raise exception 'ONLY_SHORT_CALL_OR_PUT_CAN_ROLL';
  end if;
  if p_new_expiry < current_date then raise exception 'NEW_EXPIRY_IN_PAST'; end if;
  if p_new_expiry < v_old.expiry then raise exception 'NEW_EXPIRY_MUST_NOT_BE_EARLIER'; end if;
  if lower(v_old.opt_type) = 'call' and p_new_strike < v_old.strike then raise exception 'ROLL_UP_STRIKE_REQUIRED'; end if;
  if lower(v_old.opt_type) = 'put' and p_new_strike > v_old.strike then raise exception 'ROLL_DOWN_STRIKE_REQUIRED'; end if;

  v_units := greatest(1, coalesce(v_old.qty,1)) * greatest(1, coalesce(v_old.multiplier,100));
  v_prior_chain := coalesce(v_old.premium_chain_per_share,
    coalesce(v_old.cost,0) - coalesce(v_old.open_fee,0) / v_units);
  v_chain := v_prior_chain + p_open_credit - p_close_debit
    - (coalesce(p_close_fee,0) + coalesce(p_open_fee,0)) / v_units;
  v_net_cash := (p_open_credit - p_close_debit) * v_units
    - coalesce(p_close_fee,0) - coalesce(p_open_fee,0);
  v_realized := (coalesce(v_old.cost,0) - p_close_debit) * v_units
    - coalesce(v_old.open_fee,0) - coalesce(p_close_fee,0);
  v_strategy := case when lower(v_old.opt_type) = 'call' then 'covered_call' else 'sell_put' end;

  insert into public.options_positions (
    user_id, symbol, opt_type, side, strike, expiry, cost, qty, multiplier,
    open_fee, entry_date, collateral_mode, status, opened_at, rolled_from_id,
    premium_chain_per_share, monitor_delta, delta_observation, delta_observed_at,
    watch_close_count, catalyst_confirmed, strategy_note
  ) values (
    auth.uid(), v_old.symbol, v_old.opt_type, v_old.side, p_new_strike, p_new_expiry,
    p_open_credit, v_old.qty, coalesce(v_old.multiplier,100), coalesce(p_open_fee,0),
    current_date, v_old.collateral_mode, 'open', now(), v_old.id, v_chain,
    null, null, null, 0, false, p_notes
  ) returning id into v_new_id;

  update public.options_positions set
    status = 'rolled', closed_at = now(), exit_price = p_close_debit,
    close_fee = coalesce(p_close_fee,0), realized_pnl = v_realized,
    settlement_type = 'rolled', rolled_to_id = v_new_id,
    close_notes = nullif(p_notes,'')
  where id = v_old.id;

  insert into public.option_roll_journal (
    user_id, old_position_id, new_position_id, symbol, strategy,
    old_strike, old_expiry, new_strike, new_expiry, qty, multiplier,
    close_debit, open_credit, close_fee, open_fee, net_roll_cash,
    cumulative_premium_per_share, observation_type, catalyst_confirmed, notes
  ) values (
    auth.uid(), v_old.id, v_new_id, v_old.symbol, v_strategy,
    v_old.strike, v_old.expiry, p_new_strike, p_new_expiry, v_old.qty,
    coalesce(v_old.multiplier,100), p_close_debit, p_open_credit,
    coalesce(p_close_fee,0), coalesce(p_open_fee,0), v_net_cash,
    v_chain, p_observation_type, p_catalyst_confirmed, nullif(p_notes,'')
  );

  return jsonb_build_object(
    'old_position_id', v_old.id,
    'new_position_id', v_new_id,
    'net_roll_cash', v_net_cash,
    'cumulative_premium_per_share', v_chain,
    'effective_price', case when v_strategy='covered_call' then p_new_strike + v_chain else p_new_strike - v_chain end
  );
end;
$$;

grant execute on function public.record_option_roll(bigint,numeric,date,numeric,numeric,numeric,numeric,text,boolean,text)
to authenticated;
