-- V3.2 多券商账户、累计权利金回填与部分展期。
-- 可重复执行；现有记录先归入“待分配账户”，由网页端再逐笔调整。

create table if not exists public.broker_accounts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade default auth.uid(),
  name text not null,
  broker text,
  currency text not null default 'USD',
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, name)
);

alter table public.broker_accounts enable row level security;
drop policy if exists "broker_accounts_private" on public.broker_accounts;
create policy "broker_accounts_private" on public.broker_accounts
for all using (user_id = auth.uid()) with check (user_id = auth.uid());

insert into public.broker_accounts (user_id, name, broker, sort_order)
select distinct x.user_id, '待分配账户', '未指定', 999
from (
  select user_id from public.options_positions where user_id is not null
  union
  select user_id from public.option_underlyings where user_id is not null
  union
  select user_id from public.option_roll_journal where user_id is not null
) x
on conflict (user_id, name) do nothing;

alter table public.options_positions
  add column if not exists broker_account_id bigint references public.broker_accounts(id),
  add column if not exists assignment_mode text not null default 'accept'
    check (assignment_mode in ('accept','avoid')),
  add column if not exists position_label text;

alter table public.option_underlyings
  add column if not exists broker_account_id bigint references public.broker_accounts(id);

alter table public.option_roll_journal
  add column if not exists broker_account_id bigint references public.broker_accounts(id);

update public.options_positions p
set broker_account_id = a.id
from public.broker_accounts a
where p.broker_account_id is null
  and a.user_id = p.user_id
  and a.name = '待分配账户';

update public.option_underlyings u
set broker_account_id = a.id
from public.broker_accounts a
where u.broker_account_id is null
  and a.user_id = u.user_id
  and a.name = '待分配账户';

update public.option_roll_journal j
set broker_account_id = coalesce(
  (select p.broker_account_id from public.options_positions p where p.id = j.new_position_id),
  (select p.broker_account_id from public.options_positions p where p.id = j.old_position_id),
  (select a.id from public.broker_accounts a
    where a.user_id = j.user_id and a.name = '待分配账户' limit 1)
)
where j.broker_account_id is null
  and exists (
    select 1 from public.broker_accounts a
    where a.user_id = j.user_id and a.name = '待分配账户'
  );

alter table public.options_positions alter column broker_account_id set not null;
alter table public.option_underlyings alter column broker_account_id set not null;
alter table public.option_roll_journal alter column broker_account_id set not null;

-- V3.1历史记录可能把累计权利金保留为0；以真实建仓权利金减开仓费回填。
update public.options_positions
set premium_chain_per_share = greatest(
  0,
  coalesce(cost, 0) - coalesce(open_fee, 0)
    / greatest(1, coalesce(qty, 1) * coalesce(multiplier, 100))
)
where lower(coalesce(side, '')) = 'short'
  and coalesce(cost, 0) > 0
  and (premium_chain_per_share is null or premium_chain_per_share = 0);

alter table public.option_underlyings
  drop constraint if exists option_underlyings_user_id_symbol_key;

create unique index if not exists option_underlyings_user_account_symbol_uidx
  on public.option_underlyings(user_id, broker_account_id, symbol);
create index if not exists options_positions_user_account_status_idx
  on public.options_positions(user_id, broker_account_id, status, expiry);
create index if not exists option_roll_journal_user_account_idx
  on public.option_roll_journal(user_id, broker_account_id, executed_at desc);

-- 支持整笔或部分展期。部分展期时旧仓仅扣减相应张数。
create or replace function public.record_option_roll_v32(
  p_old_position_id bigint,
  p_roll_qty integer,
  p_new_strike numeric,
  p_new_expiry date,
  p_close_debit numeric,
  p_open_credit numeric,
  p_close_fee numeric default 0,
  p_open_fee numeric default 0,
  p_observation_type text default 'close',
  p_catalyst_confirmed boolean default false,
  p_notes text default null
) returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_old public.options_positions%rowtype;
  v_new_id bigint;
  v_units numeric;
  v_prior_chain numeric;
  v_chain numeric;
  v_net_cash numeric;
  v_realized numeric;
  v_strategy text;
  v_remaining integer;
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;
  if p_roll_qty is null or p_roll_qty <= 0 then raise exception 'INVALID_ROLL_QTY'; end if;
  if p_new_strike <= 0 or p_new_expiry is null or p_close_debit < 0 or p_open_credit < 0
     or p_close_fee < 0 or p_open_fee < 0 then raise exception 'INVALID_ROLL_INPUT'; end if;
  if p_observation_type not in ('close','intraday') then raise exception 'INVALID_OBSERVATION_TYPE'; end if;

  select * into v_old from public.options_positions
  where id = p_old_position_id and user_id = auth.uid() for update;
  if not found then raise exception 'POSITION_NOT_FOUND'; end if;
  if coalesce(v_old.status, 'open') <> 'open' then raise exception 'POSITION_NOT_OPEN'; end if;
  if p_roll_qty > coalesce(v_old.qty, 1) then raise exception 'ROLL_QTY_EXCEEDS_POSITION'; end if;
  if lower(v_old.side) <> 'short' or lower(v_old.opt_type) not in ('call','put') then
    raise exception 'ONLY_SHORT_CALL_OR_PUT_CAN_ROLL';
  end if;
  if p_new_expiry < v_old.expiry then raise exception 'NEW_EXPIRY_MUST_NOT_BE_EARLIER'; end if;
  if lower(v_old.opt_type) = 'call' and p_new_strike < v_old.strike then raise exception 'ROLL_UP_STRIKE_REQUIRED'; end if;
  if lower(v_old.opt_type) = 'put' and p_new_strike > v_old.strike then raise exception 'ROLL_DOWN_STRIKE_REQUIRED'; end if;

  v_units := p_roll_qty * greatest(1, coalesce(v_old.multiplier,100));
  v_prior_chain := coalesce(v_old.premium_chain_per_share,
    coalesce(v_old.cost,0) - coalesce(v_old.open_fee,0)
      / greatest(1, coalesce(v_old.qty,1) * coalesce(v_old.multiplier,100)));
  v_chain := v_prior_chain + p_open_credit - p_close_debit
    - (coalesce(p_close_fee,0) + coalesce(p_open_fee,0)) / v_units;
  v_net_cash := (p_open_credit - p_close_debit) * v_units
    - coalesce(p_close_fee,0) - coalesce(p_open_fee,0);
  v_realized := (coalesce(v_old.cost,0) - p_close_debit) * v_units
    - coalesce(p_close_fee,0)
    - coalesce(v_old.open_fee,0) * p_roll_qty / greatest(1, coalesce(v_old.qty,1));
  v_strategy := case when lower(v_old.opt_type) = 'call' then 'covered_call' else 'sell_put' end;
  v_remaining := coalesce(v_old.qty,1) - p_roll_qty;

  insert into public.options_positions (
    user_id, broker_account_id, symbol, opt_type, side, strike, expiry, cost, qty, multiplier,
    open_fee, entry_date, collateral_mode, assignment_mode, position_label,
    status, opened_at, rolled_from_id, premium_chain_per_share,
    monitor_delta, delta_observation, delta_observed_at,
    watch_close_count, catalyst_confirmed, strategy_note
  ) values (
    auth.uid(), v_old.broker_account_id, v_old.symbol, v_old.opt_type, v_old.side,
    p_new_strike, p_new_expiry, p_open_credit, p_roll_qty,
    coalesce(v_old.multiplier,100), coalesce(p_open_fee,0), current_date,
    v_old.collateral_mode, v_old.assignment_mode, v_old.position_label,
    'open', now(), v_old.id, v_chain,
    null, null, null, 0, false, p_notes
  ) returning id into v_new_id;

  if v_remaining = 0 then
    update public.options_positions set
      status = 'rolled', closed_at = now(), exit_price = p_close_debit,
      close_fee = coalesce(p_close_fee,0), realized_pnl = v_realized,
      settlement_type = 'rolled', rolled_to_id = v_new_id,
      close_notes = nullif(p_notes,'')
    where id = v_old.id;
  else
    update public.options_positions set
      qty = v_remaining,
      open_fee = coalesce(v_old.open_fee,0) * v_remaining / greatest(1,coalesce(v_old.qty,1))
    where id = v_old.id;
  end if;

  insert into public.option_roll_journal (
    user_id, broker_account_id, old_position_id, new_position_id, symbol, strategy,
    old_strike, old_expiry, new_strike, new_expiry, qty, multiplier,
    close_debit, open_credit, close_fee, open_fee, net_roll_cash,
    cumulative_premium_per_share, observation_type, catalyst_confirmed, notes
  ) values (
    auth.uid(), v_old.broker_account_id, v_old.id, v_new_id, v_old.symbol, v_strategy,
    v_old.strike, v_old.expiry, p_new_strike, p_new_expiry, p_roll_qty,
    coalesce(v_old.multiplier,100), p_close_debit, p_open_credit,
    coalesce(p_close_fee,0), coalesce(p_open_fee,0), v_net_cash,
    v_chain, p_observation_type, p_catalyst_confirmed, nullif(p_notes,'')
  );

  return jsonb_build_object(
    'old_position_id', v_old.id,
    'new_position_id', v_new_id,
    'rolled_qty', p_roll_qty,
    'remaining_qty', v_remaining,
    'net_roll_cash', v_net_cash,
    'cumulative_premium_per_share', v_chain,
    'effective_price', case when v_strategy='covered_call'
      then p_new_strike + v_chain else p_new_strike - v_chain end
  );
end;
$$;

grant execute on function public.record_option_roll_v32(
  bigint,integer,numeric,date,numeric,numeric,numeric,numeric,text,boolean,text
) to authenticated;
