-- Learning Quality: private option state-entry observations for outcome learning.
-- Service-side snapshots are deduped by state_fingerprint; no public artifact may expose rows.

create table if not exists public.option_learning_observations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  position_id bigint not null references public.options_positions(id) on delete cascade,
  broker_account_id bigint references public.broker_accounts(id) on delete set null,
  symbol text not null,
  opt_type text not null,
  side text not null,
  strike numeric not null,
  expiry date not null,
  observed_at timestamptz not null default now(),
  risk_level text not null check (risk_level in ('l1','l2','l3','unknown')),
  risk_reason text not null,
  dte integer,
  underlying_price numeric,
  delta numeric check (delta between -1 and 1),
  spread_ratio numeric,
  state_fingerprint text not null,
  created_at timestamptz not null default now(),
  unique (user_id, position_id, state_fingerprint)
);

create index if not exists option_learning_user_observed_idx
  on public.option_learning_observations(user_id, observed_at desc);
create index if not exists option_learning_position_idx
  on public.option_learning_observations(user_id, position_id, observed_at);

alter table public.option_learning_observations enable row level security;

drop policy if exists "option_learning_owner_select" on public.option_learning_observations;
create policy "option_learning_owner_select" on public.option_learning_observations
  for select using (auth.uid() = user_id);

drop policy if exists "option_learning_owner_insert" on public.option_learning_observations;
create policy "option_learning_owner_insert" on public.option_learning_observations
  for insert with check (auth.uid() = user_id);

drop policy if exists "option_learning_owner_update" on public.option_learning_observations;
create policy "option_learning_owner_update" on public.option_learning_observations
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "option_learning_owner_delete" on public.option_learning_observations;
create policy "option_learning_owner_delete" on public.option_learning_observations
  for delete using (auth.uid() = user_id);

grant select, insert, update, delete on public.option_learning_observations to authenticated;
