-- V6.15 P1 request ledger.
-- Service-side operational counts only. No prompts, transcripts, secrets, or position details.
create table if not exists public.request_usage_ledger (
  id bigint generated by default as identity primary key,
  observed_at timestamptz not null default now(),
  provider text not null,
  request_kind text not null,
  request_count integer not null default 1 check (request_count > 0),
  paid boolean not null default false,
  source text not null,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists request_usage_ledger_observed_idx
  on public.request_usage_ledger(observed_at desc);
create index if not exists request_usage_ledger_provider_idx
  on public.request_usage_ledger(provider, observed_at desc);

alter table public.request_usage_ledger enable row level security;
-- No client policies on purpose: browser clients cannot read/write this table.
comment on table public.request_usage_ledger is
  'Service-role operational request counters only; no user content or secrets.';
