-- Private stock position ledger (#133 6083661059 B; owner-approved 2026-10-09).
-- Manual entry only: nothing is imported or copied from option_underlyings or any broker; no trading link.
-- Owner-only RLS; every row belongs to one broker account of the same owner (enforced by trigger, since a
-- foreign key alone would accept another user's account id). One open position per account+symbol.
-- Idempotent.

create table if not exists public.stock_positions (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  broker_account_id bigint not null references public.broker_accounts(id),
  symbol text not null check (symbol ~ '^[A-Z0-9.-]{1,12}$'),
  shares numeric(18,4) not null check (shares > 0),
  cost_basis numeric(18,4) check (cost_basis is null or cost_basis >= 0),
  opened_at date,
  status text not null default 'open' check (status in ('open','archived')),
  archived_at timestamptz,
  note text not null default '' check (char_length(note) <= 300),
  data_as_of timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check ((status = 'archived') = (archived_at is not null))
);

create unique index if not exists stock_positions_one_open_per_account_symbol
  on public.stock_positions (user_id, broker_account_id, symbol) where status = 'open';
create index if not exists stock_positions_user_idx on public.stock_positions (user_id, status);

create or replace function public.stock_positions_guard()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if not exists (select 1 from public.broker_accounts a where a.id = new.broker_account_id and a.user_id = new.user_id) then
    raise exception 'STOCK_POSITION_ACCOUNT_NOT_OWNED';
  end if;
  new.updated_at := now();
  return new;
end $$;

drop trigger if exists stock_positions_guard_trg on public.stock_positions;
create trigger stock_positions_guard_trg before insert or update on public.stock_positions
  for each row execute function public.stock_positions_guard();

alter table public.stock_positions enable row level security;
drop policy if exists "stock_positions_owner_select" on public.stock_positions;
create policy "stock_positions_owner_select" on public.stock_positions for select using (auth.uid() = user_id);
drop policy if exists "stock_positions_owner_insert" on public.stock_positions;
create policy "stock_positions_owner_insert" on public.stock_positions for insert with check (auth.uid() = user_id);
drop policy if exists "stock_positions_owner_update" on public.stock_positions;
create policy "stock_positions_owner_update" on public.stock_positions for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "stock_positions_owner_delete" on public.stock_positions;
create policy "stock_positions_owner_delete" on public.stock_positions for delete using (auth.uid() = user_id);

revoke all on public.stock_positions from anon;
grant select, insert, update, delete on public.stock_positions to authenticated;
